just a basic table with checkboxes, hard to approach without javascript.
cs361-spring2021-team4/TASched pull request #5
Opened 2021-04-18 01:34 UTC by tzortzos

currently, add class button does nothing, just a button atm.
wanted to mention it's not possible to verify if you have at least one checkbox is checked without javascript

2021-04-18 03:59 UTC, oldwomanjosiah requested changes
Overall, while I appreciate the contribution, this does not seem like a finished contribution to the project. It

1. does not meet the requirements of the page
2. does not comply to the stylistic standards we agreed to when we decided to use bootstrap

There are examples in the log in page for what a final page should look like and an example in the `partials/sidebar.html` of what a variadic template might look like.

2021-04-18 03:59 UTC, oldwomanjosiah commented on project/templates/create_class.html
> +    </style>
In general, since we decided to use bootstrap we will be trying to minimize the amount of custom css that we use in our templates.

2021-04-18 03:59 UTC, oldwomanjosiah commented on project/templates/create_class.html
> +    </div>
While this shows what a rendered _user list_ may look like it is missing the majority of what we need to actually create a new course in the database. Namely: A course name and a course code. This also does not take advantage of the fact that we are using Django's templating to render a variable number of items in a list like this. There is a good example in the sidebar code of doing so to create sections of HTML that are defined primarily by the code.

2021-04-18 03:59 UTC, oldwomanjosiah commented on project/templates/create_class.html
> +{% extends 'base.html' %}
This is not the correct base template, as this is a page that should only be seen by an Admin once they are logged in. See the example page that is now in the main branch and its context object for what this would look like (it is rendered using the view Index right now).

2021-04-18 04:06 UTC, tzortzos commented on project/templates/create_class.html
> +    </div>
my intention writing the code was a user list with the ability to create a class with those users, was planning on having it either having a pop-out dialogue with class name, id, etc... or having it lead to a different webpage with the TA's/instructors imported over, prompting for a class name and ID after you select them. will fix up this version since what it seems we're looking for is a singular webpage with the ability of implementing all of the info on a singular webpage.

2021-04-18 04:07 UTC, tzortzos commented on project/templates/create_class.html
> +{% extends 'base.html' %}
thanks for letting me know, wasn't sure on which template was suitable, will fix asap

2021-04-18 19:00 UTC, oldwomanjosiah commented on project/templates/create_class.html
> +    </div>
I'll look into how to best submit a form with checkboxes, this seems like a common enough case that there is probably a standard way to set the post value for the checkbox group to be a list of specific values in which case we should be able to use the primary key of the user we display as the value sent to the server.

2021-04-18 19:07 UTC, oldwomanjosiah commented on project/templates/create_class.html
> +    </div>
I'm thinking [based off this post](https://html5-tutorial.net/forms/checkboxes/) that we should be able to display a list of professor user objects consisting of the following:

- radio buttons in a list with  
  `name="professor" value="{{ user.get_id }} id="select_professor_{{ user.get_id }}"`
- label with `for="select_professor_{{ user.get_id }}"` and a value with all the relevant information

2021-04-19 20:37 UTC, Imholt approved these changes

2021-04-23 02:30 UTC, closed without merging